-- Push notifications
--
-- Events are created in the database (trigger on seasons, plus scheduled kinds
-- generated by the push-notify edge function's cron pass) and drained by the
-- edge function, which sends web push to each recipient's subscriptions.
-- dedupe_key makes every send idempotent.

-- 1) Device subscriptions. A user manages only their own rows.
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  endpoint   TEXT NOT NULL UNIQUE,
  p256dh     TEXT NOT NULL,
  auth       TEXT NOT NULL,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users manage own push subscriptions" ON public.push_subscriptions;
CREATE POLICY "Users manage own push subscriptions" ON public.push_subscriptions
  FOR ALL TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE INDEX IF NOT EXISTS push_subscriptions_user_idx ON public.push_subscriptions (user_id);

-- 2) Outbox. No client policies: only the service role (edge function) touches it.
CREATE TABLE IF NOT EXISTS public.notification_events (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id      UUID NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  season_id     UUID REFERENCES public.seasons(id) ON DELETE CASCADE,
  kind          TEXT NOT NULL,
  payload       JSONB NOT NULL DEFAULT '{}'::jsonb,
  recipient_ids UUID[],                       -- NULL = everyone on the season roster
  dedupe_key    TEXT NOT NULL UNIQUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at       TIMESTAMPTZ
);
ALTER TABLE public.notification_events ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS notification_events_unsent_idx ON public.notification_events (created_at) WHERE sent_at IS NULL;

-- 3) Who should hear about a season: its participant roster (or the whole club
--    for seasons created before rosters existed), minus placeholder profiles.
CREATE OR REPLACE FUNCTION public.season_recipient_ids(_season_id UUID)
RETURNS UUID[] AS $$
  WITH s AS (SELECT group_id FROM public.seasons WHERE id = _season_id),
  roster AS (
    SELECT sp.user_id FROM public.season_participants sp WHERE sp.season_id = _season_id
    UNION
    SELECT gm.user_id FROM public.group_members gm JOIN s ON gm.group_id = s.group_id
    WHERE NOT EXISTS (SELECT 1 FROM public.season_participants sp2 WHERE sp2.season_id = _season_id)
  )
  SELECT COALESCE(array_agg(r.user_id), '{}')
  FROM roster r
  LEFT JOIN public.profiles p ON p.user_id = r.user_id
  WHERE COALESCE(p.is_placeholder, false) = false;
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public;
REVOKE ALL ON FUNCTION public.season_recipient_ids(UUID) FROM PUBLIC, anon, authenticated;

-- 4) Phase changes and new films become events automatically.
CREATE OR REPLACE FUNCTION public.seasons_notify()
RETURNS TRIGGER AS $$
DECLARE
  film TEXT;
  base JSONB;
BEGIN
  base := jsonb_build_object('season_number', NEW.season_number, 'title', NEW.title);

  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.notification_events (group_id, season_id, kind, payload, dedupe_key)
    VALUES (NEW.group_id, NEW.id, 'season_open', base, 'season_open:' || NEW.id)
    ON CONFLICT (dedupe_key) DO NOTHING;
    RETURN NEW;
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF NEW.status = 'guessing' THEN
      INSERT INTO public.notification_events (group_id, season_id, kind, payload, dedupe_key)
      VALUES (NEW.group_id, NEW.id, 'guessing_open', base, 'guessing_open:' || NEW.id)
      ON CONFLICT (dedupe_key) DO NOTHING;
    ELSIF NEW.status = 'watching' THEN
      SELECT p.title INTO film FROM public.movie_picks p
      WHERE p.season_id = NEW.id AND p.watch_order = NEW.current_movie_index LIMIT 1;
      INSERT INTO public.notification_events (group_id, season_id, kind, payload, dedupe_key)
      VALUES (NEW.group_id, NEW.id, 'watching_open',
              base || jsonb_build_object('film', film, 'next_call_date', NEW.next_call_date),
              'next_film:' || NEW.id || ':' || NEW.current_movie_index)
      ON CONFLICT (dedupe_key) DO NOTHING;
    ELSIF NEW.status = 'reviewing' THEN
      INSERT INTO public.notification_events (group_id, season_id, kind, payload, dedupe_key)
      VALUES (NEW.group_id, NEW.id, 'review_open', base, 'review_open:' || NEW.id)
      ON CONFLICT (dedupe_key) DO NOTHING;
    ELSIF NEW.status = 'completed' THEN
      INSERT INTO public.notification_events (group_id, season_id, kind, payload, dedupe_key)
      VALUES (NEW.group_id, NEW.id, 'season_complete', base, 'season_complete:' || NEW.id)
      ON CONFLICT (dedupe_key) DO NOTHING;
    END IF;
  ELSIF NEW.status = 'watching' AND NEW.current_movie_index IS DISTINCT FROM OLD.current_movie_index THEN
    SELECT p.title INTO film FROM public.movie_picks p
    WHERE p.season_id = NEW.id AND p.watch_order = NEW.current_movie_index LIMIT 1;
    INSERT INTO public.notification_events (group_id, season_id, kind, payload, dedupe_key)
    VALUES (NEW.group_id, NEW.id, 'next_film',
            base || jsonb_build_object('film', film, 'next_call_date', NEW.next_call_date),
            'next_film:' || NEW.id || ':' || NEW.current_movie_index)
    ON CONFLICT (dedupe_key) DO NOTHING;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS seasons_notify ON public.seasons;
CREATE TRIGGER seasons_notify
  AFTER INSERT OR UPDATE ON public.seasons
  FOR EACH ROW EXECUTE FUNCTION public.seasons_notify();
